### ISSUE TITLE
TypeError: Object doesn't support property or method 'slice'

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#163]
https://sentry.io/epimorphics-ltd/lr-ukhpi/issues/434573183/

```


@MalcolmShazell This looks like a Windows 10 error. It's Pembrokeshire for the last 12 months. I've tried it on my browser, but it worked OK. Can you try it on yours please?

TypeError: Object doesn't support property or method 'slice'
  at createScales (./app/javascript/presenters/data-graph.js:142:9)
  at configureAxes (./app/javascript/presenters/data-graph.js:178:3)
  at drawGraph (./app/javascript/presenters/data-graph.js:394:3)
...
(7 additional frame(s) were not displayed)
```

**Comment by ijdickinson** [comment]
Duplicate issue #169. I'll close this one, and keep updates and comments on the other one.
